/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package treesetnetbeans;

import java.util.Collections;
import java.util.TreeSet;
import javax.swing.JOptionPane;

/**
 *
 * @author daniel
 */
public class tresetgui extends javax.swing.JFrame {

    /**
     * Creates new form tresetgui
     */
    public tresetgui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        listId = new java.awt.List();
        listNombre = new java.awt.List();
        listPrecio = new java.awt.List();
        jButtonAnnadir = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        listId.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listIdMouseClicked(evt);
            }
        });
        listId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listIdActionPerformed(evt);
            }
        });

        listNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listNombreMouseClicked(evt);
            }
        });
        listNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listNombreActionPerformed(evt);
            }
        });

        listPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listPrecioMouseClicked(evt);
            }
        });
        listPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPrecioActionPerformed(evt);
            }
        });

        jButtonAnnadir.setText("Annadir");
        jButtonAnnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnadirActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAnnadir)
                    .addComponent(listId, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminar))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listId, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAnnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        listId.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void recargar(){
        
        listId.removeAll();
        listNombre.removeAll();
        listPrecio.removeAll();
        
        for (Producto producto : lista){
        
            listId.add(String.valueOf(producto.getId()));
            listNombre.add(producto.getNombre());
            listPrecio.add(String.valueOf(producto.getPrecio()));
        
        }
        
    }
    
    private void listNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listNombreActionPerformed

    private void listNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listNombreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listNombreMouseClicked

    private void listIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listIdActionPerformed

    }//GEN-LAST:event_listIdActionPerformed

    private void listIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listIdMouseClicked

    }//GEN-LAST:event_listIdMouseClicked

    private void listPrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listPrecioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listPrecioMouseClicked

    private void listPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listPrecioActionPerformed

    private void jButtonAnnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnadirActionPerformed

        String idstr = JOptionPane.showInputDialog("Inserta el ID");

        if (idstr == null) {

            //JOptionPane.showMessageDialog(null, "Operación cancelada.");
            JOptionPane.showMessageDialog(null, "Operación cancelada.", "", JOptionPane.WARNING_MESSAGE);

            return; // interesante
        }
        
        int id;

        try {

            id = Integer.parseInt(idstr);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Inserta un numero valido", "", JOptionPane.WARNING_MESSAGE);
            return;

        }

        String nombre = JOptionPane.showInputDialog("Inserta el Nombre");

        if (nombre == null) {

            //JOptionPane.showMessageDialog(null, "Operación cancelada.");
            JOptionPane.showMessageDialog(null, "Operación cancelada.", "", JOptionPane.WARNING_MESSAGE);

            return;
        }

        String preciostr = JOptionPane.showInputDialog("Inserta el precio");

        if (preciostr == null) {

            //JOptionPane.showMessageDialog(null, "Operación cancelada.");
            JOptionPane.showMessageDialog(null, "Operación cancelada.", "", JOptionPane.WARNING_MESSAGE);

            return;
        }
        
        float precio;
        
         try {

            precio = Float.parseFloat(preciostr);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Inserta un numero valido", "", JOptionPane.WARNING_MESSAGE);
            return;

        }
         
         Producto producto = new Producto (id, nombre, precio);
         
         boolean annadido = lista.add(producto);
         
         if (!annadido){
             
             JOptionPane.showMessageDialog(null, "El producto esta repetido", "", JOptionPane.WARNING_MESSAGE);
           
         }
         
         recargar();

        //JOptionPane.showMessageDialog(null, id);

    }//GEN-LAST:event_jButtonAnnadirActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
      
        String idstr = JOptionPane.showInputDialog("Inserta el ID");

        if (idstr == null) {

            //JOptionPane.showMessageDialog(null, "Operación cancelada.");
            JOptionPane.showMessageDialog(null, "Operación cancelada.", "", JOptionPane.WARNING_MESSAGE);

            return; // interesante
        }
        
        int id;

        try {

            id = Integer.parseInt(idstr);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Inserta un numero valido", "", JOptionPane.WARNING_MESSAGE);
            return;

        }
        
        Producto eliminable = null;
        
        for(Producto producto : lista){
            
            if(producto.getId() == id) eliminable = producto;
        
        }
        
        if(eliminable  == null) {
            JOptionPane.showMessageDialog(null, "No existe un producto con ese id", "", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        lista.remove(eliminable);
        
        recargar();
            
        
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tresetgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tresetgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tresetgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tresetgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tresetgui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnadir;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JPanel jPanel1;
    private java.awt.List listId;
    private java.awt.List listNombre;
    private java.awt.List listPrecio;
    // End of variables declaration//GEN-END:variables

    TreeSet<Producto> lista = new TreeSet<Producto>(Collections.reverseOrder());

}
