/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pruebapractica;

import java.sql.*;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daniel
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        initBD();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextFecha = new javax.swing.JTextField();
        boxPista = new javax.swing.JComboBox<>();
        boxDuracion = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        boxHora = new javax.swing.JComboBox<>();
        insertar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Pista");

        textNombre.setText("Test");

        jLabel3.setText("Fecha(YYY-MM-DD)");

        jLabel4.setText("Duracion");

        TextFecha.setText("2000-02-02");
        TextFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFechaActionPerformed(evt);
            }
        });

        boxPista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pista 1", "Pista 2", "Pista 3", "Pista 4", "Pista 5", "Pista 6", "Pista 7" }));
        boxPista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxPistaActionPerformed(evt);
            }
        });

        boxDuracion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "60", "120" }));
        boxDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxDuracionActionPerformed(evt);
            }
        });

        jLabel5.setText("Hora");

        boxHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00" }));
        boxHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxHoraActionPerformed(evt);
            }
        });

        insertar.setText("Insertar");
        insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"09:00", null, null, null, null, null, null},
                {"10:00", null, null, null, null, null, null},
                {"11:00", null, null, null, null, null, null},
                {"12:00", null, null, null, null, null, null},
                {"13:00", null, null, null, null, null, null},
                {"14:00", null, null, null, null, null, null},
                {"15:00", null, null, null, null, null, null},
                {"16:00", null, null, null, null, null, null},
                {"17:00", null, null, null, null, null, null},
                {"18:00", null, null, null, null, null, null},
                {"19:00", null, null, null, null, null, null},
                {"20:00", null, null, null, null, null, null}
            },
            new String [] {
                "Hora", "Pista 1", "Pista 2", "Pista 3", "Pista 4", "Pista 5", "Pista 6"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jButton2.setText("Mostrar dia");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(boxPista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(boxDuracion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(boxHora, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(insertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(TextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(boxHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(boxPista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initBD() {

        LocalDate fecha = LocalDate.parse(TextFecha.getText());

        String sql = "SELECT * FROM reservas WHERE fecha = '" + fecha + "'";

        try {
            String url = "jdbc:mysql://localhost:3306/Pistas";
            String usuario = "admin";
            String contrasenna = "root";
            conn = DriverManager.getConnection(url, usuario, contrasenna);
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    ///////////////////////////////////////////////////////////////////////////////////////////
    private void recargarDia() {

        initBD();

        Tabla.clearSelection();

        DefaultTableModel model = (DefaultTableModel) Tabla.getModel();

        LocalDate fecha = LocalDate.parse(TextFecha.getText());

        String sql = "SELECT * FROM reservas WHERE fecha = '" + fecha + "'";

        for (int columna = 0; columna <= 11; columna++) {

            for (int fila = 1; fila <= 6; fila++) {

                model.setValueAt("", columna, fila);

            }

        }

        //model.setRowCount(12);
        //model.setValueAt("tst", 4, 1);
        try {

            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            // Mientras haya filas, las agregamos
            while (rs.next()) {
                System.out.println(rs.toString());
                // Suponiendo que 'reservas' tiene las columnas id, nombre y hora
                int id = rs.getInt("id");
                String nombre = rs.getString("nombre");
                int pista = rs.getInt("pista");
                String horastr = rs.getString("hora");
                int hora = conversorHora(horastr);
                //Reserva reserva = new Reserva(id, nombre, pista,) //model.setValueAt("Reservado", fila, columna);
                model.setValueAt(nombre, hora, pista);
                System.out.println(nombre);
                System.out.println(pista);
                System.out.println(hora);

            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    ///////////////////////////////////////////////////////////////////////////////////////////

    public int conversorHora(String hora) {
        // Partimos la hora usando ":"
        String[] partes = hora.split(":");

        // Obtenemos la hora como número
        int horas = Integer.parseInt(partes[0]);

        // Suponiendo que tu tabla empieza en 9:00
        int fila = horas - 9;

        return fila;
    }

    private void boxPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxPistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxPistaActionPerformed

    private void insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarActionPerformed

        String nombre = textNombre.getText();
        String pista = (String) boxPista.getSelectedItem();
        LocalDate fecha = LocalDate.parse(TextFecha.getText()); // Extrae la fecha de TextFecha
        LocalTime hora = LocalTime.parse(boxHora.getSelectedItem().toString()); // Extrae la hora de boxHora
        int duracion = Integer.parseInt(boxDuracion.getSelectedItem().toString()); // Duración (60 o 120)

        LocalDateTime fechaHora = LocalDateTime.of(fecha, hora);

        Reserva reserva = new Reserva(nombre, pista, fechaHora, duracion);

        String sql = "INSERT INTO reservas (nombre, fecha, pista, hora, duracion) VALUES (?, ?, ?, ?, ?)";

        try {

            PreparedStatement stmt = conn.prepareStatement(sql);

            stmt.setString(1, reserva.getNombre());

            stmt.setDate(2, java.sql.Date.valueOf(reserva.getFecha().toLocalDate()));

            stmt.setInt(3, reserva.getPista());
   
            stmt.setTime(4, java.sql.Time.valueOf(reserva.getFecha().toLocalTime()));
    
            stmt.setInt(5, reserva.getDuracion());
            
            stmt.executeUpdate();
            
            recargarDia();

        } catch (Exception e) {

            e.printStackTrace();

        }


    }//GEN-LAST:event_insertarActionPerformed

    private void boxDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxDuracionActionPerformed

    private void TextFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFechaActionPerformed

    private void boxHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxHoraActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        recargarDia();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JTextField TextFecha;
    private javax.swing.JComboBox<String> boxDuracion;
    private javax.swing.JComboBox<String> boxHora;
    private javax.swing.JComboBox<String> boxPista;
    private javax.swing.JButton insertar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables

    Connection conn;

}
